# Falkon OS pacman.conf - 100% Arch-совместимый
# Отличия от ванильного Arch: ParallelDownloads, Color, ILoveCandy, multilib вкл.

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
ILoveCandy
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Опционально: Chaotic-AUR для бинарных пакетов (yay/paru, ядра). Закомментировано по умолчанию
# чтобы сохранить чистую совместимость с Arch. Раскомментируй в falkon-welcome при желании.
#[chaotic-aur]
#Include = /etc/pacman.d/chaotic-mirrorlist
